name: Verify

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 13 * * 1-5"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Verify patch
        run: |
          make verify-patch
      - name: Verify patch format
        run: |
          make verify-patch-format

  Test-v1-24-0-lts-0:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-24-0-lts-0
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.24.0-lts.0
        run: |
          make v1.24.0-lts.0
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-v1-23-5-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-23-5-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.23.5-lts.1
        run: |
          make v1.23.5-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-24-0-lts-0:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-24-0-lts-0
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.24.0-lts.0
        run: |
          make v1.24.0-lts.0
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Cmd-v1-23-5-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-23-5-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.23.5-lts.1
        run: |
          make v1.23.5-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-24-0-lts-0:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-24-0-lts-0
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.24.0-lts.0
        run: |
          make v1.24.0-lts.0
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  Test-Integration-v1-23-5-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-23-5-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.23.5-lts.1
        run: |
          make v1.23.5-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  Test-v1-22-8-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-22-8-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.22.8-lts.1
        run: |
          make v1.22.8-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-22-8-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-22-8-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.22.8-lts.1
        run: |
          make v1.22.8-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-22-8-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-22-8-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.22.8-lts.1
        run: |
          make v1.22.8-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  Test-v1-21-11-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-21-11-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.21.11-lts.1
        run: |
          make v1.21.11-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-21-11-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-21-11-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.21.11-lts.1
        run: |
          make v1.21.11-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-21-11-lts-1:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-21-11-lts-1
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.21.11-lts.1
        run: |
          make v1.21.11-lts.1
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  Test-v1-20-15-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-15-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.15-lts.2
        run: |
          make v1.20.15-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-20-15-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-15-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.15-lts.2
        run: |
          make v1.20.15-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-20-15-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-15-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.15-lts.2
        run: |
          make v1.20.15-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration

  Test-v1-20-2-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-2-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.2-lts.2
        run: |
          make v1.20.2-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test
        run: |
          make test

  Test-Cmd-v1-20-2-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-2-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.2-lts.2
        run: |
          make v1.20.2-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test cmd
        run: |
          make test-cmd

  Test-Integration-v1-20-2-lts-2:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: src
        with:
          path: |
            src
            /tmp/kubernetes-lts/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-20-2-lts-2
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout to v1.20.2-lts.2
        run: |
          make v1.20.2-lts.2
      - name: Install etcd
        run: |
          make install-etcd
      - name: Test integration
        run: |
          make test-integration
